### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by vteromero** [vteromero/VTEnc#8]
- [x] Tests for random sequences #15 
- [x] Refactor of `count_zeros_at_bit_pos`* functions to improve encoding performance #16 
- [x] Fix bug on wrongly using `memcmp` on some testing programs #17 #14 
- [x] Encode lower bits for clusters of length 1 #18
